// demo/react/components/PredictiveAddressInput.tsx
// Data8 Predictive Address API Documentation
// https://docs.data-8.co.uk/web-services/predictiveaddress

import createClient from "openapi-fetch";
import React, { forwardRef, useEffect, useId, useRef, useState } from "react";
import { PredictiveAddress } from "@data8/types";
import { getErrorMessage } from "../../helpers/ApiError";

type SearchResults = NonNullable<PredictiveAddress.components["schemas"]["PredictiveAddressSearchResponse"]["Results"]>;
type RetrieveResult = PredictiveAddress.components["schemas"]["PredictiveAddressRetrieveResponse"];

const DEFAULT_APPLICATION_NAME = "@data8/react-predictiveaddress";

export type PredictiveAddressRetrieveOptions = Record<string, unknown>;

/**
 * Slot props that customize the internal DOM elements without replacing the
 * predictive search behavior.
 */
export interface PredictiveAddressInputSlots {
  /** Props merged onto the outer wrapper element. */
  root?: React.HTMLAttributes<HTMLDivElement>;
  /** Props merged onto the textbox element. */
  input?: React.InputHTMLAttributes<HTMLInputElement>;
  /** Props merged onto the dropdown list element. */
  dropdown?: React.HTMLAttributes<HTMLUListElement>;
  /** Props merged onto each dropdown option row. */
  option?: React.LiHTMLAttributes<HTMLLIElement>;
  /** Props merged onto each dropdown option row while hovered. */
  optionHover?: React.LiHTMLAttributes<HTMLLIElement>;
  /** Props merged onto the embedded current-location button. */
  currentLocationButton?: React.ButtonHTMLAttributes<HTMLButtonElement>;
  /** Props merged onto the inline error message. */
  errorMessage?: React.HTMLAttributes<HTMLParagraphElement>;
}

/**
 * Props for the reusable Predictive Address textbox.
 *
 * Use `defaultValue` for an initial value that the user can later edit freely,
 * or `value` plus `onChange` for a fully controlled input.
 */
export interface PredictiveAddressInputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, "defaultValue" | "value" | "onChange"> {
  /** Data8 API key used for lookup requests. */
  apiKey: string;
  /** ISO2 country code used for search and retrieve requests. */
  country: string;
  /** Show a clickable current-location icon inside the textbox when the selected country supports geocoding. */
  showCurrentLocation?: boolean;
  /** Application name reported in Data8 request options; defaults to `@data8/react-predictiveaddress`. */
  applicationName?: string;
  /** Optional geocoding support flag from the host; when omitted, this control resolves support internally. */
  supportsGeocoding?: boolean;
  /** Optional retrieve options object passed directly to the Data8 retrieve endpoint. */
  retrieveOptions?: PredictiveAddressRetrieveOptions;
  /** Resolves the text shown in the textbox after a selection is made. */
  getDisplayText?: (result: RetrieveResult) => string;
  /** Themeable slot props for the internal DOM structure. */
  slots?: PredictiveAddressInputSlots;
  /** Controlled textbox value. */
  value?: string;
  /** Initial textbox value for uncontrolled usage. */
  defaultValue?: string;
  /** Standard textbox change handler. */
  onChange?: React.ChangeEventHandler<HTMLInputElement>;
  /** Called when the user selects a full address result. */
  onSelectedAddress: (result: RetrieveResult) => void;
}

const client = createClient<PredictiveAddress.paths>({
  baseUrl: "https://webservices.data-8.co.uk",
});

async function search(
  address: string,
  apiKey: string,
  country: string,
  sessionId: string | null,
  applicationName: string,
  signal?: AbortSignal
) {
  const { data, error } = await client.POST("/PredictiveAddress/Search.json", {
    signal,
    headers: { "content-type": "application/json" },
    body: {
      username: "apikey-" + apiKey,
      search: address,
      country,
      session: sessionId ?? undefined,
      options: {
        ApplicationName: applicationName,
      },
    },
  });
  if (error) throw error;
  if (!data?.Status?.Success) {
    throw new Error(data?.Status?.ErrorMessage ?? "Predictive address search failed");
  }
  return data;
}

async function drilldown(id: string, apiKey: string, country: string, applicationName: string) {
  const { data, error } = await client.POST("/PredictiveAddress/DrillDown.json", {
    headers: { "content-type": "application/json" },
    body: {
      username: "apikey-" + apiKey,
      country,
      id,
      options: {
        ApplicationName: applicationName,
      },
    },
  });
  if (error) throw error;
  if (!data?.Status?.Success) {
    throw new Error(data?.Status?.ErrorMessage ?? "Predictive address drilldown failed");
  }
  return data;
}

async function retrieve(
  id: string,
  apiKey: string,
  country: string,
  applicationName: string,
  retrieveOptions?: PredictiveAddressRetrieveOptions
) {
  const { data, error } = await client.POST("/PredictiveAddress/Retrieve.json", {
    headers: { "content-type": "application/json" },
    body: {
      username: "apikey-" + apiKey,
      country,
      id,
      options: {
        ApplicationName: applicationName,
        ...(retrieveOptions ?? {}),
      },
    },
  });
  if (error) throw error;
  if (!data?.Status?.Success) {
    throw new Error(data?.Status?.ErrorMessage ?? "Predictive address retrieve failed");
  }
  return data;
}

function mergeRefs<T>(...refs: Array<React.Ref<T> | undefined>) {
  return (value: T | null) => {
    for (const ref of refs) {
      if (!ref) continue;
      if (typeof ref === "function") {
        ref(value);
      } else {
        (ref as React.MutableRefObject<T | null>).current = value;
      }
    }
  };
}

export const PredictiveAddressInput = forwardRef<HTMLInputElement, PredictiveAddressInputProps>(
  function PredictiveAddressInput(
    {
      apiKey,
      country,
      showCurrentLocation = false,
      applicationName = DEFAULT_APPLICATION_NAME,
      supportsGeocoding,
      retrieveOptions,
      getDisplayText,
      slots,
      value,
      defaultValue,
      onChange,
      onSelectedAddress,
      disabled,
      onFocus,
      onBlur,
      onKeyDown,
      placeholder = "Enter Address",
      style,
      ...inputProps
    },
    ref
  ) {
    const [internalValue, setInternalValue] = useState(defaultValue ?? "");
    const [searchQuery, setSearchQuery] = useState<string | null>(null);
    const [options, setOptions] = useState<SearchResults>([]);
    const [isResultsOpen, setIsResultsOpen] = useState(false);
    const [highlightedOptionIndex, setHighlightedOptionIndex] = useState<number | null>(null);
    const [resolvedSupportsGeocoding, setResolvedSupportsGeocoding] = useState(false);
    const [isLocating, setIsLocating] = useState(false);
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
    const sessionIdRef = useRef<string | null>(null);
    const suppressNextSearchRef = useRef(false);
    const activeSearchController = useRef<AbortController | null>(null);
    const interactionRequestId = useRef(0);
    const resultsContainerRef = useRef<HTMLDivElement | null>(null);
    const listboxRef = useRef<HTMLUListElement | null>(null);
    const inputRef = useRef<HTMLInputElement | null>(null);
    const listboxId = useId();

    const currentValue = value ?? internalValue;
    const activeQuery = searchQuery ?? currentValue;

    const rootSlotProps = slots?.root ?? {};
    const inputSlotProps = slots?.input ?? {};
    const dropdownSlotProps = slots?.dropdown ?? {};
    const optionSlotProps = slots?.option ?? {};
    const optionHoverSlotProps = slots?.optionHover ?? {};
    const currentLocationButtonSlotProps = slots?.currentLocationButton ?? {};
    const errorMessageSlotProps = slots?.errorMessage ?? {};
    const canUseCurrentLocation = supportsGeocoding ?? resolvedSupportsGeocoding;

    useEffect(() => {
      if (supportsGeocoding !== undefined) {
        return;
      }

      let isActive = true;

      void (async () => {
        try {
          const { data, error } = await client.POST("/PredictiveAddress/GetSupportedCountries.json", {
            headers: { "content-type": "application/json" },
            body: {
              username: "apikey-" + apiKey,
              options: {
                ApplicationName: applicationName,
              },
            },
          });
          if (error) throw error;
          if (!data?.Status?.Success) {
            throw new Error(data?.Status?.ErrorMessage ?? "Loading supported countries failed");
          }
          if (!isActive) return;

          const supported = (data?.Countries ?? []).filter((item) => item.ISO2 && item.SupportsGeocoding);
          setResolvedSupportsGeocoding(supported.some((item) => item.ISO2 === country));
        } catch (error) {
          if (isActive) {
            setResolvedSupportsGeocoding(false);
            setErrorMessage(getErrorMessage(error, "Error loading supported countries"));
          }
        }
      })();

      return () => {
        isActive = false;
      };
    }, [apiKey, applicationName, country, supportsGeocoding]);

    useEffect(() => {
      setOptions([]);
      setIsResultsOpen(false);
      setHighlightedOptionIndex(null);
      sessionIdRef.current = null;
      setSearchQuery(null);
      setErrorMessage(null);
      setIsLocating(false);
      interactionRequestId.current += 1;
      activeSearchController.current?.abort();
    }, [country, apiKey]);

    useEffect(() => {
      function handlePointerDown(event: PointerEvent) {
        const target = event.target as Node | null;
        if (!resultsContainerRef.current || !target) return;

        if (!resultsContainerRef.current.contains(target)) {
          setIsResultsOpen(false);
        }
      }

      document.addEventListener("pointerdown", handlePointerDown);
      return () => {
        document.removeEventListener("pointerdown", handlePointerDown);
      };
    }, []);

    useEffect(() => {
      setErrorMessage(null);
      if (suppressNextSearchRef.current) {
        suppressNextSearchRef.current = false;
        return;
      }

      activeSearchController.current?.abort();

      if (activeQuery.length === 0 || disabled) {
        setOptions([]);
        setIsResultsOpen(false);
        setHighlightedOptionIndex(null);
        return;
      }

      const controller = new AbortController();
      activeSearchController.current = controller;

      const timeoutId = window.setTimeout(() => {
        search(activeQuery, apiKey, country, sessionIdRef.current, applicationName, controller.signal)
          .then((res) => {
            if (controller.signal.aborted) return;
            sessionIdRef.current = res?.SessionID ?? null;
            setOptions(res?.Results ?? []);
            setHighlightedOptionIndex(null);
            setIsResultsOpen((res?.Results?.length ?? 0) > 0);
          })
          .catch((error: unknown) => {
            if (error instanceof DOMException && error.name === "AbortError") return;
            if (controller.signal.aborted) return;
            setErrorMessage(getErrorMessage(error, "Error searching predictive address"));
            setOptions([]);
            setIsResultsOpen(false);
          });
      }, 250);

      return () => {
        window.clearTimeout(timeoutId);
        controller.abort();
        if (activeSearchController.current === controller) {
          activeSearchController.current = null;
        }
      };
    }, [activeQuery, apiKey, applicationName, country, disabled]);

    function handleUseCurrentLocation() {
      const requestId = ++interactionRequestId.current;
      // Keep keyboard interaction anchored to the textbox so arrow keys
      // control the listbox instead of scrolling the page.
      inputRef.current?.focus();

      if (!navigator.geolocation) {
        setErrorMessage("Geolocation is not supported by this browser.");
        return;
      }

      setIsLocating(true);
      setErrorMessage(null);

      navigator.geolocation.getCurrentPosition(
        (position) => {
          if (requestId !== interactionRequestId.current) return;
          const latitude = position.coords.latitude.toFixed(6);
          const longitude = position.coords.longitude.toFixed(6);
          setSearchQuery(`${latitude}, ${longitude}`);
          setIsResultsOpen(false);
          inputRef.current?.focus();
          setIsLocating(false);
        },
        (error) => {
          if (requestId !== interactionRequestId.current) return;
          setErrorMessage(error.message || "Unable to retrieve your location.");
          setIsLocating(false);
        }
      );
    }

    async function handleSelect(option: SearchResults[number]) {
      const requestId = ++interactionRequestId.current;
      setErrorMessage(null);
      setIsLocating(false);
      let res: RetrieveResult | null | undefined;
      try {
        if (option.container) {
          const drilldownResult = await drilldown(option.value ?? "", apiKey, country, applicationName);
          if (requestId !== interactionRequestId.current) return;
          sessionIdRef.current = drilldownResult?.SessionID ?? null;
          setOptions(drilldownResult?.Results ?? []);
          setHighlightedOptionIndex(null);
          setIsResultsOpen((drilldownResult?.Results?.length ?? 0) > 0);
          return;
        }

        res = await retrieve(option.value ?? "", apiKey, country, applicationName, retrieveOptions);
      } catch (error) {
        if (requestId === interactionRequestId.current) {
          setErrorMessage(getErrorMessage(error, "Error loading the selected address"));
        }
        return;
      }
      if (requestId !== interactionRequestId.current) return;
      if (!res) {
        setOptions([]);
        setIsResultsOpen(false);
        return;
      }

      suppressNextSearchRef.current = true;
      setInternalValue(getDisplayText?.(res) ?? res.Result?.Address?.Lines?.[0] ?? option.label ?? currentValue);
      setSearchQuery(null);
      setOptions([]);
      setHighlightedOptionIndex(null);
      setIsResultsOpen(false);
      onSelectedAddress(res);
    }

    useEffect(() => {
      if (!isResultsOpen || highlightedOptionIndex == null) {
        return;
      }

      const optionElement = listboxRef.current?.querySelector<HTMLElement>(`#${listboxId}-option-${highlightedOptionIndex}`);
      optionElement?.scrollIntoView({ block: "nearest" });
    }, [highlightedOptionIndex, isResultsOpen, listboxId]);

    return (
      <div
        {...rootSlotProps}
        ref={resultsContainerRef}
        style={{ ...rootSlotProps.style }}
      >
        <div style={{ position: "relative" }}>
        {showCurrentLocation && canUseCurrentLocation && (
          <button
            {...currentLocationButtonSlotProps}
            type="button"
            onMouseDown={(event) => {
              event.stopPropagation();
              currentLocationButtonSlotProps.onMouseDown?.(event);
            }}
            onClick={handleUseCurrentLocation}
            disabled={isLocating || disabled}
            title={currentLocationButtonSlotProps.title ?? "Use current location"}
            aria-label={currentLocationButtonSlotProps["aria-label"] ?? "Use current location"}
            style={{
              position: "absolute",
              right: "0.35rem",
              top: "50%",
              transform: "translateY(-50%)",
              zIndex: 2,
              width: "1.8rem",
              height: "1.8rem",
              borderRadius: "999px",
              border: "1px solid var(--data8-border)",
              background: "var(--data8-white)",
              color: "var(--data8-ink)",
              display: "inline-flex",
              alignItems: "center",
              justifyContent: "center",
              boxShadow: "0 1px 2px rgba(15, 23, 42, 0.08)",
              cursor: isLocating || disabled ? "not-allowed" : "pointer",
              ...currentLocationButtonSlotProps.style,
            }}
          >
            ⦿
          </button>
        )}
        <input
          {...inputProps}
          {...inputSlotProps}
          ref={mergeRefs(ref, inputRef)}
          type={inputProps.type ?? "text"}
          role="combobox"
          aria-expanded={isResultsOpen}
          aria-haspopup="listbox"
          aria-owns={isResultsOpen ? listboxId : undefined}
          aria-autocomplete="list"
          aria-activedescendant={highlightedOptionIndex != null ? `${listboxId}-option-${highlightedOptionIndex}` : undefined}
          value={currentValue}
          disabled={disabled}
          placeholder={placeholder}
          autoComplete={inputProps.autoComplete ?? "off"}
          style={{
            marginBottom: 0,
            boxShadow: "none",
            paddingRight: showCurrentLocation && canUseCurrentLocation ? "2.4rem" : undefined,
            ...style,
            ...inputSlotProps.style,
          }}
          onFocus={(event) => {
            setIsResultsOpen(options.length > 0);
            onFocus?.(event);
          }}
          onBlur={onBlur}
          onKeyDown={(event) => {
            if (isResultsOpen && options.length > 0) {
              if (event.key === "ArrowDown") {
                event.preventDefault();
                setHighlightedOptionIndex((current) => (current == null ? 0 : Math.min(current + 1, options.length - 1)));
              }

              if (event.key === "ArrowUp") {
                event.preventDefault();
                setHighlightedOptionIndex((current) => {
                  if (current == null) return null;
                  if (current <= 0) {
                    inputRef.current?.focus();
                    return null;
                  }
                  return current - 1;
                });
              }

              if (event.key === "Enter" && highlightedOptionIndex != null) {
                event.preventDefault();
                void handleSelect(options[highlightedOptionIndex]);
              }
            }

            if (event.key === "Escape") {
              setIsResultsOpen(false);
              setHighlightedOptionIndex(null);
            }
            onKeyDown?.(event);
          }}
          onChange={(event) => {
            if (value === undefined) {
              setInternalValue(event.target.value);
            }
            interactionRequestId.current += 1;
            setIsLocating(false);
            setErrorMessage(null);
            setSearchQuery(null);
            setIsResultsOpen(true);
            onChange?.(event);
          }}
        />
        {isResultsOpen && options.length > 0 && (
          <ul
            {...dropdownSlotProps}
            ref={listboxRef}
            id={listboxId}
            role="listbox"
            style={{
              position: "absolute",
              top: "calc(100% + 0.25rem)",
              left: 0,
              right: 0,
              zIndex: 20,
              margin: 0,
              padding: 0,
              listStyle: "none",
              border: "1px solid var(--data8-border)",
              borderRadius: "0 0 4px 4px",
              background: "var(--data8-white)",
              maxHeight: "250px",
              overflowY: "auto",
              boxShadow: "0 12px 30px rgba(15, 23, 42, 0.12)",
              ...dropdownSlotProps.style,
            }}
          >
            {options.map((option, index) => (
              <li
                {...optionSlotProps}
                key={`${option.value}-${index}`}
                role="option"
                id={`${listboxId}-option-${index}`}
                aria-selected={highlightedOptionIndex === index}
                className={
                  highlightedOptionIndex === index
                    ? [optionSlotProps.className, optionHoverSlotProps.className].filter(Boolean).join(" ")
                    : optionSlotProps.className
                }
                style={{
                  padding: "0.5rem",
                  cursor: "pointer",
                  borderBottom: "1px solid var(--data8-border)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  gap: "0.5rem",
                  background: highlightedOptionIndex === index ? "#eaf1ff" : option.container ? "#f6f9ff" : undefined,
                  fontWeight: option.container ? 600 : undefined,
                  ...optionSlotProps.style,
                  ...(highlightedOptionIndex === index ? optionHoverSlotProps.style : undefined),
                }}
                onMouseEnter={(event) => {
                  setHighlightedOptionIndex(index);
                  optionSlotProps.onMouseEnter?.(event);
                  optionHoverSlotProps.onMouseEnter?.(event);
                }}
                onMouseLeave={(event) => {
                  setHighlightedOptionIndex((current) => (current === index ? null : current));
                  optionSlotProps.onMouseLeave?.(event);
                  optionHoverSlotProps.onMouseLeave?.(event);
                }}
                onMouseDown={(event) => {
                  event.preventDefault();
                  event.stopPropagation();
                  optionSlotProps.onMouseDown?.(event);
                }}
                onClick={(event) => {
                  event.preventDefault();
                  event.stopPropagation();
                  optionSlotProps.onClick?.(event);
                  setHighlightedOptionIndex(null);
                  void handleSelect(option);
                }}
              >
                <span>{option.label}</span>
                {option.container && (
                  <span
                    style={{
                      display: "inline-flex",
                      alignItems: "center",
                      justifyContent: "center",
                      minWidth: "1.6rem",
                      height: "1.6rem",
                      padding: "0 0.45rem",
                      borderRadius: "999px",
                      background: "#dbe8ff",
                      color: "#163c96",
                      fontSize: "0.75rem",
                      lineHeight: 1,
                      fontWeight: 700,
                      flexShrink: 0,
                    }}
                    aria-label={option.items ? `${option.items} items available` : "Contains additional results"}
                    title={option.items ? `${option.items} items` : "More results"}
                  >
                    {typeof option.items === "number" && option.items > 0 ? option.items : ">"}
                  </span>
                )}
              </li>
            ))}
          </ul>
        )}
        </div>
        {errorMessage && (
          <p
            {...errorMessageSlotProps}
            style={{
              margin: "0.35rem 0 0",
              color: "var(--data8-invalid)",
              fontSize: "0.875rem",
              ...errorMessageSlotProps.style,
            }}
          >
            {errorMessage}
          </p>
        )}
      </div>
    );
  }
);

export type { RetrieveResult };

// demo/vue/components/PredictiveAddressInput.vue
<!-- Data8 Predictive Address API Documentation
https://docs.data-8.co.uk/web-services/predictiveaddress -->

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, useAttrs, useId, watch } from "vue";
import type { ButtonHTMLAttributes, HTMLAttributes, InputHTMLAttributes, LiHTMLAttributes } from "vue";
import createClient from "openapi-fetch";
import type { PredictiveAddress } from "@data8/types";
import { getErrorMessage } from "../../helpers/ApiError";

export type RetrieveResult = PredictiveAddress.components["schemas"]["PredictiveAddressRetrieveResponse"];
export type PredictiveAddressRetrieveOptions = Record<string, unknown>;
type SearchResults = NonNullable<PredictiveAddress.components["schemas"]["PredictiveAddressSearchResponse"]["Results"]>;

const DEFAULT_APPLICATION_NAME = "Data8VueDemo";

export interface PredictiveAddressInputSlots {
  root?: HTMLAttributes;
  input?: InputHTMLAttributes;
  dropdown?: HTMLAttributes;
  option?: LiHTMLAttributes;
  optionHover?: LiHTMLAttributes;
  currentLocationButton?: ButtonHTMLAttributes;
  errorMessage?: HTMLAttributes;
}

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<{
  apiKey: string;
  country: string;
  modelValue?: string;
  defaultValue?: string;
  showCurrentLocation?: boolean;
  applicationName?: string;
  supportsGeocoding?: boolean;
  retrieveOptions?: PredictiveAddressRetrieveOptions;
  getDisplayText?: (result: RetrieveResult) => string;
  slots?: PredictiveAddressInputSlots;
  disabled?: boolean;
  placeholder?: string;
}>(), {
  defaultValue: "",
  showCurrentLocation: false,
  applicationName: DEFAULT_APPLICATION_NAME,
  supportsGeocoding: undefined,
  disabled: false,
  placeholder: "Enter Address",
});

const emit = defineEmits<{
  "update:modelValue": [value: string];
  selectedAddress: [result: RetrieveResult];
}>();
const attrs = useAttrs();
const inputAttrs = computed(() => {
  const { onFocus, onBlur, onInput, onKeydown, onKeyDown, ...inputAttributes } = attrs;
  return inputAttributes;
});
const inputSlotProps = computed(() => {
  const { onFocus, onBlur, onInput, onKeydown, ...inputAttributes } = props.slots?.input ?? {};
  return inputAttributes;
});
const optionSlotProps = computed(() => {
  const {
    onMouseenter, onMouseleave, onMousedown, onClick, ...optionAttributes
  } = props.slots?.option ?? {};
  return optionAttributes;
});
const currentLocationButtonSlotProps = computed(() => {
  const { onMousedown, onClick, ...buttonAttributes } = props.slots?.currentLocationButton ?? {};
  return buttonAttributes;
});
const client = createClient<PredictiveAddress.paths>({ baseUrl: "https://webservices.data-8.co.uk" });
const internalValue = ref(props.defaultValue);
const currentValue = computed(() => props.modelValue ?? internalValue.value);
const searchQuery = ref<string | null>(null);
const options = ref<SearchResults>([]);
const isResultsOpen = ref(false);
const highlightedOptionIndex = ref<number | null>(null);
const resolvedSupportsGeocoding = ref(false);
const canUseCurrentLocation = computed(() => props.supportsGeocoding ?? resolvedSupportsGeocoding.value);
const isLocating = ref(false);
const errorMessage = ref<string | null>(null);
const rootRef = ref<HTMLDivElement | null>(null);
const inputRef = ref<HTMLInputElement | null>(null);
const listboxRef = ref<HTMLUListElement | null>(null);
const listboxId = useId();
let sessionId: string | null = null;
let searchController: AbortController | null = null;
let interactionRequestId = 0;
let suppressSearch = false;

defineExpose({ input: inputRef, focus: () => inputRef.value?.focus() });

function clearResults() {
  options.value = [];
  isResultsOpen.value = false;
  highlightedOptionIndex.value = null;
}

function invokeAttributeHandler(name: string, event: Event) {
  const handler = attrs[name] as ((event: Event) => void) | Array<(event: Event) => void> | undefined;
  if (Array.isArray(handler)) {
    handler.forEach((callback) => callback(event));
  } else {
    handler?.(event);
  }
}

function invokeSlotHandler(slot: Record<string, unknown> | undefined, name: string, event: Event) {
  const handler = slot?.[name] as ((event: Event) => void) | Array<(event: Event) => void> | undefined;
  if (Array.isArray(handler)) {
    handler.forEach((callback) => callback(event));
  } else {
    handler?.(event);
  }
}

watch(() => [props.country, props.apiKey], () => {
  sessionId = null;
  searchQuery.value = null;
  errorMessage.value = null;
  isLocating.value = false;
  interactionRequestId += 1;
  searchController?.abort();
  clearResults();
}, { flush: "sync" });

watch(() => [props.apiKey, props.country, props.applicationName, props.supportsGeocoding], async (_, __, onCleanup) => {
  resolvedSupportsGeocoding.value = false;
  if (props.supportsGeocoding !== undefined) return;

  const controller = new AbortController();
  onCleanup(() => controller.abort());
  try {
    const { data, error } = await client.POST("/PredictiveAddress/GetSupportedCountries.json", {
      signal: controller.signal,
      headers: { "content-type": "application/json" },
      body: {
        username: "apikey-" + props.apiKey,
        options: { ApplicationName: props.applicationName },
      },
    });
    if (error) throw error;
    if (!data?.Status?.Success) throw new Error(data?.Status?.ErrorMessage ?? "Loading supported countries failed");
    if (controller.signal.aborted) return;
    resolvedSupportsGeocoding.value = (data.Countries ?? []).some(
      (country) => country.ISO2 === props.country && country.SupportsGeocoding
    );
  } catch (error) {
    if (!controller.signal.aborted) {
      errorMessage.value = getErrorMessage(error, "Error loading supported countries");
    }
  }
}, { immediate: true });

watch(
  [currentValue, searchQuery, () => props.apiKey, () => props.country, () => props.applicationName, () => props.disabled],
  (_, __, onCleanup) => {
    errorMessage.value = null;
    if (suppressSearch) return;
    clearResults();

    const query = searchQuery.value ?? currentValue.value;
    if (!query.length || props.disabled) return;

    const controller = new AbortController();
    searchController = controller;
    const timeoutId = window.setTimeout(async () => {
      try {
        const { data, error } = await client.POST("/PredictiveAddress/Search.json", {
          signal: controller.signal,
          headers: { "content-type": "application/json" },
          body: {
            username: "apikey-" + props.apiKey,
            search: query,
            country: props.country,
            session: sessionId ?? undefined,
            options: { ApplicationName: props.applicationName },
          },
        });
        if (error) throw error;
        if (!data?.Status?.Success) throw new Error(data?.Status?.ErrorMessage ?? "Predictive address search failed");
        if (controller.signal.aborted) return;
        sessionId = data.SessionID ?? null;
        options.value = data.Results ?? [];
        highlightedOptionIndex.value = null;
        isResultsOpen.value = options.value.length > 0;
      } catch (error) {
        if (controller.signal.aborted) return;
        errorMessage.value = getErrorMessage(error, "Error searching predictive address");
        clearResults();
      }
    }, 250);
    onCleanup(() => {
      window.clearTimeout(timeoutId);
      controller.abort();
      if (searchController === controller) searchController = null;
    });
  },
  { immediate: true }
);

function handleInput(event: Event) {
  const value = (event.target as HTMLInputElement).value;
  if (props.modelValue === undefined) internalValue.value = value;
  interactionRequestId += 1;
  isLocating.value = false;
  errorMessage.value = null;
  searchQuery.value = null;
  isResultsOpen.value = true;
  emit("update:modelValue", value);
  invokeAttributeHandler("onInput", event);
}

function handleFocus(event: FocusEvent) {
  isResultsOpen.value = options.value.length > 0;
  invokeAttributeHandler("onFocus", event);
}

function handleBlur(event: FocusEvent) {
  invokeAttributeHandler("onBlur", event);
}

function handleCurrentLocationMouseDown(event: MouseEvent) {
  invokeSlotHandler(props.slots?.currentLocationButton as Record<string, unknown> | undefined, "onMousedown", event);
}

function handleOptionMouseEnter(index: number, event: MouseEvent) {
  highlightedOptionIndex.value = index;
  invokeSlotHandler(props.slots?.option as Record<string, unknown> | undefined, "onMouseenter", event);
  invokeSlotHandler(props.slots?.optionHover as Record<string, unknown> | undefined, "onMouseenter", event);
}

function handleOptionMouseLeave(index: number, event: MouseEvent) {
  if (highlightedOptionIndex.value === index) highlightedOptionIndex.value = null;
  invokeSlotHandler(props.slots?.option as Record<string, unknown> | undefined, "onMouseleave", event);
  invokeSlotHandler(props.slots?.optionHover as Record<string, unknown> | undefined, "onMouseleave", event);
}

function handleOptionMouseDown(event: MouseEvent) {
  event.preventDefault();
  event.stopPropagation();
  invokeSlotHandler(props.slots?.option as Record<string, unknown> | undefined, "onMousedown", event);
}

function handleOptionClick(option: SearchResults[number], event: MouseEvent) {
  event.preventDefault();
  event.stopPropagation();
  invokeSlotHandler(props.slots?.option as Record<string, unknown> | undefined, "onClick", event);
  highlightedOptionIndex.value = null;
  void handleSelect(option);
}

function handleUseCurrentLocation() {
  const requestId = ++interactionRequestId;
  inputRef.value?.focus();
  if (!navigator.geolocation) {
    errorMessage.value = "Geolocation is not supported by this browser.";
    return;
  }
  isLocating.value = true;
  errorMessage.value = null;
  navigator.geolocation.getCurrentPosition(
    (position) => {
      if (requestId !== interactionRequestId) return;
      searchQuery.value = `${position.coords.latitude.toFixed(6)}, ${position.coords.longitude.toFixed(6)}`;
      isResultsOpen.value = false;
      inputRef.value?.focus();
      isLocating.value = false;
    },
    (error) => {
      if (requestId !== interactionRequestId) return;
      errorMessage.value = error.message || "Unable to retrieve your location.";
      isLocating.value = false;
    }
  );
}

async function handleSelect(option: SearchResults[number]) {
  const requestId = ++interactionRequestId;
  isLocating.value = false;
  errorMessage.value = null;
  const body = {
    username: "apikey-" + props.apiKey,
    country: props.country,
    id: option.value ?? "",
    options: { ApplicationName: props.applicationName },
  };
  try {
    if (option.container) {
      const { data, error } = await client.POST("/PredictiveAddress/DrillDown.json", {
        headers: { "content-type": "application/json" },
        body,
      });
      if (error) throw error;
      if (!data?.Status?.Success) throw new Error(data?.Status?.ErrorMessage ?? "Predictive address drilldown failed");
      if (requestId !== interactionRequestId) return;
      sessionId = data.SessionID ?? null;
      options.value = data.Results ?? [];
      highlightedOptionIndex.value = null;
      isResultsOpen.value = options.value.length > 0;
      return;
    }

    const { data, error } = await client.POST("/PredictiveAddress/Retrieve.json", {
      headers: { "content-type": "application/json" },
      body: { ...body, options: { ...body.options, ...props.retrieveOptions } },
    });
    if (error) throw error;
    if (!data?.Status?.Success) throw new Error(data?.Status?.ErrorMessage ?? "Predictive address retrieve failed");
    if (requestId !== interactionRequestId) return;

    const value = props.getDisplayText?.(data) ?? data.Result?.Address?.Lines?.[0] ?? option.label ?? currentValue.value;
    suppressSearch = true;
    internalValue.value = value;
    searchQuery.value = null;
    clearResults();
    emit("update:modelValue", value);
    emit("selectedAddress", data);
    await nextTick();
    suppressSearch = false;
  } catch (error) {
    if (requestId === interactionRequestId) {
      errorMessage.value = getErrorMessage(error, "Error loading the selected address");
    }
  }
}

function handleKeyDown(event: KeyboardEvent) {
  if (isResultsOpen.value && options.value.length) {
    if (event.key === "ArrowDown") {
      event.preventDefault();
      highlightedOptionIndex.value = highlightedOptionIndex.value === null
        ? 0 : Math.min(highlightedOptionIndex.value + 1, options.value.length - 1);
    } else if (event.key === "ArrowUp") {
      event.preventDefault();
      if (highlightedOptionIndex.value !== null && highlightedOptionIndex.value <= 0) {
        inputRef.value?.focus();
        highlightedOptionIndex.value = null;
      } else if (highlightedOptionIndex.value !== null) {
        highlightedOptionIndex.value -= 1;
      }
    } else if (event.key === "Enter" && highlightedOptionIndex.value !== null) {
      event.preventDefault();
      void handleSelect(options.value[highlightedOptionIndex.value]);
    }
  }
  if (event.key === "Escape") {
    isResultsOpen.value = false;
    highlightedOptionIndex.value = null;
  }
  invokeAttributeHandler("onKeydown", event);
  invokeAttributeHandler("onKeyDown", event);
}

watch([highlightedOptionIndex, isResultsOpen], () => {
  if (isResultsOpen.value && highlightedOptionIndex.value !== null) {
    const option = listboxRef.value?.children[highlightedOptionIndex.value];
    option?.scrollIntoView({ block: "nearest" });
  }
}, { flush: "post" });

function handlePointerDown(event: PointerEvent) {
  if (event.target instanceof Node && !rootRef.value?.contains(event.target)) {
    isResultsOpen.value = false;
  }
}

onMounted(() => document.addEventListener("pointerdown", handlePointerDown));
onBeforeUnmount(() => {
  document.removeEventListener("pointerdown", handlePointerDown);
  searchController?.abort();
  interactionRequestId += 1;
});
</script>

<template>
  <div v-bind="slots?.root" ref="rootRef">
    <div style="position: relative">
      <button
        v-if="showCurrentLocation && canUseCurrentLocation"
        v-bind="currentLocationButtonSlotProps"
        class="current-location"
        type="button"
        :disabled="isLocating || disabled"
        :title="slots?.currentLocationButton?.title ?? 'Use current location'"
        :aria-label="slots?.currentLocationButton?.['aria-label'] ?? 'Use current location'"
        @mousedown.stop="handleCurrentLocationMouseDown"
        @click="handleUseCurrentLocation"
      >
        &#10687;
      </button>
      <input
        v-bind="{ ...inputAttrs, ...inputSlotProps }"
        ref="inputRef"
        :type="slots?.input?.type ?? (attrs.type as InputHTMLAttributes['type']) ?? 'text'"
        role="combobox"
        :aria-expanded="isResultsOpen"
        aria-haspopup="listbox"
        :aria-owns="isResultsOpen ? listboxId : undefined"
        aria-autocomplete="list"
        :aria-activedescendant="highlightedOptionIndex !== null ? `${listboxId}-option-${highlightedOptionIndex}` : undefined"
        :value="currentValue"
        :disabled="disabled"
        :placeholder="placeholder"
        :autocomplete="slots?.input?.autocomplete ?? (attrs.autocomplete as InputHTMLAttributes['autocomplete']) ?? 'off'"
        :style="[
          { marginBottom: 0, boxShadow: 'none', paddingRight: showCurrentLocation && canUseCurrentLocation ? '2.4rem' : undefined },
          attrs.style as HTMLAttributes['style'], slots?.input?.style,
        ]"
        @input="handleInput"
        @focus="handleFocus"
        @blur="handleBlur"
        @keydown="handleKeyDown"
      />
      <ul
        v-if="isResultsOpen && options.length"
        v-bind="slots?.dropdown"
        :id="listboxId"
        ref="listboxRef"
        class="address-results"
        role="listbox"
      >
        <li
          v-for="(option, index) in options"
          :id="`${listboxId}-option-${index}`"
          :key="`${option.value}-${index}`"
          v-bind="optionSlotProps"
          role="option"
          :aria-selected="highlightedOptionIndex === index"
          :class="[slots?.option?.class, { container: option.container, highlighted: highlightedOptionIndex === index }, highlightedOptionIndex === index ? slots?.optionHover?.class : undefined]"
          :style="[slots?.option?.style, highlightedOptionIndex === index ? slots?.optionHover?.style : undefined]"
          @mouseenter="handleOptionMouseEnter(index, $event)"
          @mouseleave="handleOptionMouseLeave(index, $event)"
          @mousedown="handleOptionMouseDown"
          @click="handleOptionClick(option, $event)"
        >
          <span>{{ option.label }}</span>
          <span
            v-if="option.container"
            class="result-count"
            :aria-label="option.items ? `${option.items} items available` : 'Contains additional results'"
            :title="option.items ? `${option.items} items` : 'More results'"
          >{{ typeof option.items === 'number' && option.items > 0 ? option.items : '>' }}</span>
        </li>
      </ul>
    </div>
    <p v-if="errorMessage" v-bind="slots?.errorMessage" class="address-error">{{ errorMessage }}</p>
  </div>
</template>

<style scoped>
.current-location {
  position: absolute;
  right: 0.35rem;
  top: 50%;
  transform: translateY(-50%);
  z-index: 2;
  width: 1.8rem;
  height: 1.8rem;
  padding: 0;
  margin: 0;
  border-radius: 999px;
  border: 1px solid var(--data8-border);
  background: var(--data8-white);
  color: var(--data8-ink);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 1px 2px rgba(15, 23, 42, 0.08);
  cursor: pointer;
}
.current-location:disabled { cursor: not-allowed; }
.address-results {
  position: absolute;
  top: calc(100% + 0.25rem);
  left: 0;
  right: 0;
  z-index: 20;
  margin: 0;
  padding: 0;
  list-style: none;
  border: 1px solid var(--data8-border);
  border-radius: 0 0 4px 4px;
  background: var(--data8-white);
  color: var(--data8-ink);
  max-height: 250px;
  overflow-y: auto;
  box-shadow: 0 12px 30px rgba(15, 23, 42, 0.12);
}
.address-results li {
  margin: 0;
  padding: 0.5rem;
  list-style: none;
  cursor: pointer;
  border-bottom: 1px solid var(--data8-border);
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 0.5rem;
  overflow-wrap: anywhere;
}
.address-results li.container { background: #f6f9ff; font-weight: 600; }
.address-results li.highlighted { background: #eaf1ff; }
.result-count {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 1.6rem;
  height: 1.6rem;
  padding: 0 0.45rem;
  border-radius: 999px;
  background: #dbe8ff;
  color: #163c96;
  font-size: 0.75rem;
  line-height: 1;
  font-weight: 700;
  flex-shrink: 0;
}
.address-error { margin: 0.35rem 0 0; color: var(--data8-invalid); font-size: 0.875rem; }
</style>
